spring:
  datasource:
    url: jdbc:postgresql://34.64.96.102:5432/just-alpha-db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        diarect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace